### ISSUE TITLE
build_resnet_bifpn_backbone seems broken?

### ISSUE THREAD

**Issue by jinfagang** [xingyizhou/CenterNet2#58]
I set:

```
RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"] # fpn produce 4 levels, only using 3 for now
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 3
    NUM_BIFPN: 4
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 512
```
seems have error in build bi-fpn:

```
modeling/backbone/bifpn.py", line 201, in __init__
    input_reduction = fpn_config['nodes'][node_idx]['reduction']
IndexError: list index out of range

```
